steps:
  # see https://www.npmjs.com/package/editorconfig-checker
  - id: eclint
    name: "e53e225/editorconfig-checker"

  - id: go_version
    name: "gcr.io/cloud-builders/go"
    args: ["version"]
    env: ["GOPATH=."]

  - id: go_linter
    name: "golangci/golangci-lint"
    args: ["golangci-lint","run"]

  - id: go_security
    name: "securego/gosec"
    args: ["helloworld"]
    env: ["GOPATH=."]

  - id: deployment
    name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/compute-engine-project-254107/golang-cd:$REVISION_ID", "-f", "Dockerfile", "."]
images:
  - "gcr.io/compute-engine-project-254107/golang-cd:$REVISION_ID"